interface SRSData {
  nextReviewDate: number; // Timestamp of the next scheduled review
  interval: number; // Current interval in days
  repetitions: number; // Number of successful repetitions
  easeFactor: number; // Ease factor for SM-2 algorithm
  lastReviewed: number; // Timestamp of the last review
  createdAt: number; // Timestamp when the item was added
  updatedAt: number; // Timestamp when the item was last updated
}

interface VocabularyItem {
  id: string; // Unique identifier
  targetLanguageWord: string; // The word/phrase in the target language
  englishTranslation: string; // English translation
  pronunciationAudioUrl?: string; // Optional URL to a custom audio file, or generated by TTS
  tags?: string[]; // Optional categories or tags
  srsData: SRSData; // Spaced Repetition System data
}
