/**
 * Core vocabulary item interface following the plan specification
 */
export interface VocabularyItem {
  /** Unique identifier for the vocabulary item */
  id: string;
  
  /** The word/phrase in Hindi */
  targetLanguageWord: string;
  
  /** English translation */
  englishTranslation: string;
  
  /** Optional URL to a custom audio file, or generated by TTS */
  pronunciationAudioUrl?: string;
  
  /** Optional categories or tags */
  tags?: string[];
  
  /** Spaced Repetition System metadata */
  srsData: SRSData;
}

/**
 * Spaced Repetition System data for SM-2 algorithm
 */
export interface SRSData {
  /** Timestamp of the next scheduled review */
  nextReviewDate: number;
  
  /** Current interval in days */
  interval: number;
  
  /** Number of successful repetitions */
  repetitions: number;
  
  /** Ease factor for SM-2 algorithm (default: 2.5) */
  easeFactor: number;
  
  /** Timestamp of the last review */
  lastReviewed: number;
  
  /** Timestamp when the item was added */
  createdAt: number;
  
  /** Timestamp when the item was last updated */
  updatedAt: number;
  
  // Speed Learn extensions
  /** Current stage in the Speed Learn process */
  speedLearnStage: SpeedLearnStage;
  
  /** Number of times word was heard in Speed Learn mode */
  exposureCount: number;
  
  /** Timestamp when item was mastered (passed quiz) */
  masteredAt?: number;
  
  /** Timestamp of last Speed Learn session */
  lastSpeedLearnSession?: number;
}

/**
 * Review session data
 */
export interface ReviewSession {
  /** ID of the vocabulary item being reviewed */
  itemId: string;
  
  /** Timestamp when the review started */
  startTime: number;
  
  /** Timestamp when the review ended */
  endTime?: number;
  
  /** User's response quality (1: Again, 2: Hard, 3: Good, 4: Easy) */
  quality?: ReviewQuality;
  
  /** Time taken to respond in milliseconds */
  responseTime?: number;
}

/**
 * Review quality enum based on SM-2 algorithm
 */
export enum ReviewQuality {
  Again = 1, // Complete blackout, incorrect response
  Hard = 2,  // Correct response recalled with serious difficulty
  Good = 3,  // Correct response after a hesitation
  Easy = 4,  // Perfect response
}

/**
 * Speed Learn stages based on linguistic psychology (fully automatic)
 */
export enum SpeedLearnStage {
  NEW = 'new',                        // Just added, not yet in Speed Learn
  PASSIVE_LEARNING = 'passive_learning', // Currently in auto-play cycle
  MASTERED = 'mastered',                 // Automatically mastered after sufficient exposures
  LONG_TERM_REVIEW = 'long_term_review'  // In spaced review cycle
}

/**
 * Speed Learn session configuration
 */
export interface SpeedLearnConfig {
  /** Number of repetitions per session (2-5) */
  repetitionsPerSession: number;
  
  /** Pause between Hindi and English (milliseconds) */
  wordPause: number;
  
  /** Pause between different words (milliseconds) */
  sentencePause: number;
  
  /** Maximum words per session to prevent cognitive overload */
  maxWordsPerSession: number;
  
  /** Enable background music (alpha waves) */
  enableBackgroundMusic: boolean;
  
  /** TTS speed multiplier (0.5 - 2.0) */
  speechSpeed: number;
  
  /** Automatically master word after N exposures (no quiz required) */
  exposuresBeforeMastery: number;
}

/**
 * Speed Learn session data
 */
export interface SpeedLearnSession {
  /** Session ID */
  id: string;
  
  /** Session start timestamp */
  startTime: number;
  
  /** Session end timestamp */
  endTime?: number;
  
  /** Items played in this session */
  itemsPlayed: string[];
  
  /** Number of repetitions completed */
  repetitionsCompleted: number;
  
  /** Session was completed vs manually stopped */
  completed: boolean;
  
  /** Total duration in milliseconds */
  duration?: number;
}

/**
 * Learning statistics interface
 */
export interface LearningStats {
  /** Total number of vocabulary items */
  totalItems: number;
  
  /** Number of items due for review today */
  dueToday: number;
  
  /** Number of new items added today */
  newToday: number;
  
  /** Number of items reviewed today */
  reviewedToday: number;
  
  /** Overall accuracy rate (0-1) */
  accuracyRate: number;
  
  /** Current learning streak in days */
  streak: number;
  
  /** Total review sessions completed */
  totalReviews: number;
}

/**
 * User configuration interface
 */
export interface UserConfig {
  /** Preferred TTS voice */
  ttsVoice: string;
  
  /** Speech rate (0.1 - 10) */
  speechRate: number;
  
  /** Speech pitch (0 - 2) */
  speechPitch: number;
  
  /** Enable notifications */
  notificationsEnabled: boolean;
  
  /** Notification quiet hours start (24-hour format) */
  quietHoursStart: number;
  
  /** Notification quiet hours end (24-hour format) */
  quietHoursEnd: number;
  
  /** Target language code */
  targetLanguage: string;
  
  /** New word repetitions before considering learned */
  newWordRepetitions: number;
  
  /** Daily review time in hours (24-hour format) */
  dailyReviewTime: number;
  
  /** Enable daily review reminders */
  reviewRemindersEnabled: boolean;
  
  /** Speed Learn configuration */
  speedLearnConfig: SpeedLearnConfig;
}
